version: "2"
services:
  hub:
    build: .
    volumes:

      - ./development/run.sh:/data/run.sh

      # Utilize custom certs 
      - ./development/hub/cert:/data/vendor/simplesamlphp/simplesamlphp/cert

      # Utilize custom configs
      - ./development/hub/config/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php
#      - ./development/hub/config/config.php:/data/vendor/simplesamlphp/simplesamlphp/config/config.php

      # Utilize custom metadata
      - ./development/hub/metadata/idp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/idp-remote.php
      - ./development/hub/metadata/saml20-idp-hosted.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-hosted.php
      - ./development/hub/metadata/saml20-sp-hosted.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-sp-hosted.php
      - ./development/hub/metadata/sp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/sp-remote.php

      # Override the initial SSOService.php file, to ensure this module is used
      - ./sspoverrides/www_saml2_idp/SSOService.php:/data/vendor/simplesamlphp/simplesamlphp/www/saml2/idp/SSOService.php

      # Utilize this module's files
      - ./lib:/data/vendor/simplesamlphp/simplesamlphp/modules/sildisco/lib
      - ./www:/data/vendor/simplesamlphp/simplesamlphp/modules/sildisco/www
      - ./tests:/data/vendor/simplesamlphp/simplesamlphp/modules/sildisco/tests

      # Configure the debugger
      - ./development/hub/run-debug.sh:/data/run-debug.sh
    command: /data/run-debug.sh 
    ports:
      - "80:80"
    environment:
      - ADMIN_EMAIL=john_doe@there.com
      - ADMIN_PASS=1234qwer
      - SECRET_SALT=h57fjemb&d$n^nsJFGNjweJ
      - SECURE_COOKIE=false
      - ADMIN_PROTECT_INDEX_PAGE=false
      - SHOW_SAML_ERRORS=true
      - ENABLE_HUB_AUTHPROCS=true

  idp1:
    image: silintl/ssp-base
    volumes:
      - ./development/run.sh:/data/run.sh

      # Utilize custom certs
      - ./development/idp-local/cert:/data/vendor/simplesamlphp/simplesamlphp/cert

      # Utilize custom configs
      - ./development/idp-local/config/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php
      - ./development/idp-local/config/config.php:/data/vendor/simplesamlphp/simplesamlphp/config/config.php

      # Utilize custom metadata
      - ./development/idp-local/metadata/saml20-idp-hosted.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-hosted.php
      - ./development/idp-local/metadata/saml20-sp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-sp-remote.php
    command: /data/run.sh
    ports:
      - "8085:80"
    environment:
      - ADMIN_EMAIL=john_doe@there.com
      - ADMIN_PASS=a
      - SECRET_SALT=h57fjemb&d$n^nsJFGNjweJ
      - SECURE_COOKIE=false
      - SHOW_SAML_ERRORS=true

  idp2:
    image: silintl/ssp-base
    volumes:
      - ./development/run.sh:/data/run.sh

      # Utilize custom certs
      - ./development/idp2-local/cert:/data/vendor/simplesamlphp/simplesamlphp/cert

      # Utilize custom configs
      - ./development/idp2-local/config/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php
      - ./development/idp2-local/config/config.php:/data/vendor/simplesamlphp/simplesamlphp/config/config.php

      # Utilize custom metadata
      - ./development/idp2-local/metadata/saml20-idp-hosted.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-hosted.php
      - ./development/idp2-local/metadata/saml20-sp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-sp-remote.php
    command: /data/run.sh
    ports:
      - "8086:80"
    environment:
      - ADMIN_EMAIL=john_doe@there.com
      - ADMIN_PASS=b
      - SECRET_SALT=h57fjemb&d$n^nsJFGNjweJ
      - SECURE_COOKIE=false
      - SHOW_SAML_ERRORS=true


  sp1:
    image: silintl/ssp-base
    volumes:
      # Utilize custom certs
      - ./development/sp-local/cert:/data/vendor/simplesamlphp/simplesamlphp/cert

      # Utilize custom configs
      - ./development/sp-local/config/config.php:/data/vendor/simplesamlphp/simplesamlphp/config/config.php
      - ./development/sp-local/config/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php

      # Utilize custom metadata
      - ./development/sp-local/metadata/saml20-idp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-remote.php
    ports:
      - "8081:80"
    environment:
      - ADMIN_EMAIL=john_doe@there.com
      - ADMIN_PASS=sp1
      - SECRET_SALT=h57fjemb&d$n^nsJFGNjweJz1
      - SECURE_COOKIE=false
      - SHOW_SAML_ERRORS=true
      - SAML20_IDP_ENABLE=false
      - ADMIN_PROTECT_INDEX_PAGE=false


  sp2:
    image: silintl/ssp-base
    volumes:
      # Utilize custom certs
      - ./development/sp2-local/cert:/data/vendor/simplesamlphp/simplesamlphp/cert

      # Utilize custom configs
      - ./development/sp2-local/config/config.php:/data/vendor/simplesamlphp/simplesamlphp/config/config.php
      - ./development/sp2-local/config/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php

      # Utilize custom metadata
      - ./development/sp2-local/metadata/saml20-idp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-remote.php
    ports:
      - "8082:80"
    environment:
      - ADMIN_EMAIL=john_doe@there.com
      - ADMIN_PASS=sp2
      - SECRET_SALT=h57fjemb&d$n^nsJFGNjweJz2
      - SECURE_COOKIE=false
      - SHOW_SAML_ERRORS=true
      - SAML20_IDP_ENABLE=false
      - ADMIN_PROTECT_INDEX_PAGE=false


  sp3:
    image: silintl/ssp-base
    volumes:
      # Utilize custom certs
      - ./development/sp3-local/cert:/data/vendor/simplesamlphp/simplesamlphp/cert

      # Utilize custom configs
      - ./development/sp3-local/config/config.php:/data/vendor/simplesamlphp/simplesamlphp/config/config.php
      - ./development/sp3-local/config/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php

      # Utilize custom metadata
      - ./development/sp3-local/metadata/saml20-idp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-remote.php
    ports:
      - "8083:80"
    environment:
      - ADMIN_EMAIL=john_doe@there.com
      - ADMIN_PASS=sp3
      - SECRET_SALT=h57fjemb&d$n^nsJFGNjweJz3
      - SECURE_COOKIE=false
      - SHOW_SAML_ERRORS=true
      - SAML20_IDP_ENABLE=false
      - ADMIN_PROTECT_INDEX_PAGE=false
      
  hub4tests:
    build: .
    volumes:

      - ./development/run.sh:/data/run.sh

      # Utilize custom certs 
      - ./development/hub4tests/cert:/data/vendor/simplesamlphp/simplesamlphp/cert

      # Utilize custom configs
      - ./development/hub4tests/config/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php
#      - ./development/hub4tests/config/config.php:/data/vendor/simplesamlphp/simplesamlphp/config/config.php

      # Utilize custom metadata
      - ./development/hub4tests/metadata/idp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/idp-remote.php
      - ./development/hub4tests/metadata/saml20-idp-hosted.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-hosted.php
      - ./development/hub4tests/metadata/saml20-sp-hosted.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-sp-hosted.php
      - ./development/hub4tests/metadata/sp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/sp-remote.php

      # Override the initial SSOService.php file, to ensure this module is used
      - ./sspoverrides/www_saml2_idp/SSOService.php:/data/vendor/simplesamlphp/simplesamlphp/www/saml2/idp/SSOService.php

      # Utilize this module's files
      - ./lib:/data/vendor/simplesamlphp/simplesamlphp/modules/sildisco/lib
      - ./www:/data/vendor/simplesamlphp/simplesamlphp/modules/sildisco/www
      - ./tests:/data/vendor/simplesamlphp/simplesamlphp/modules/sildisco/tests

      # Configure the debugger
      - ./development/hub4tests/run-debug.sh:/data/run-debug.sh
    command: /data/run-debug.sh 
    ports:
      - "8090:80"
    environment:
      - ADMIN_EMAIL=john_doe@there.com
      - ADMIN_PASS=1234qwer
      - SECRET_SALT=h57fjemb&d$n^nsJFGNjweJ
      - SECURE_COOKIE=false
      - ADMIN_PROTECT_INDEX_PAGE=false
      - SHOW_SAML_ERRORS=true
      - ENABLE_HUB_AUTHPROCS=true     


  browser_test:
    build: ./development/browser_test/
    volumes:
      - ./development/codeception.yml:/data/codeception.yml
      - ./development/codeception/tests:/data/tests
    depends_on:
      - phantomjs       
    ports:
      - "8091:80"  

  phantomjs:
    image: davert/phantomjs-env:latest
    ports:
      - "4444"
    entrypoint:
      - phantomjs
      - --webdriver=4444
      - --ignore-ssl-errors=true
      - --load-images=false   
